version: '3.7'
services:
  db:
    build: './db'
    restart: always
    hostname: postgress
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    name: inversify-showcase
    driver_opts:
      com.docker.network.bridge.name: inversify-sc
